/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.camillacarvalho.projetos.janelas;

import com.camillacarvalho.projetos.entidades.Fornecedor;
import com.camillacarvalho.projetos.entidades.Usuario;
import static com.camillacarvalho.projetos.janelas.HomeController.listaUsuarios;
import static com.camillacarvalho.projetos.janelas.HomeController.print;
import static com.camillacarvalho.projetos.janelas.HomeController.setListaUsuarios;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Camilla Carvalho, Fatec Botucatu 2022
 */
public final class CadastroFonecedores extends javax.swing.JFrame {

    private List<Fornecedor> listaForcedoresCadastrados;

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroFonecedores() {
        initComponents();
        carregarDados();
        //jComboListaUsuarios.addItem();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanelFornecedores = new javax.swing.JPanel();
        jComboListaFornecedores = new javax.swing.JComboBox<>();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonFecharTelaFornecedor = new javax.swing.JButton();
        jButtonSalvarFornecedor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelUsuarioId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextCNPJ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextSetor = new javax.swing.JTextField();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPasswordField2.setText("jPasswordField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelFornecedores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do Fornecedor"));
        jPanelFornecedores.setToolTipText("");

        jComboListaFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboListaFornecedoresActionPerformed(evt);
            }
        });

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Senha:");

        jLabel3.setText("Login:");

        jLabel5.setText("Fornecedores");

        jButtonFecharTelaFornecedor.setText("FECHAR");
        jButtonFecharTelaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharTelaFornecedorActionPerformed(evt);
            }
        });

        jButtonSalvarFornecedor.setText("SALVAR");
        jButtonSalvarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarFornecedorActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Id:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabelUsuarioId.setText("0");

        jLabel8.setText("CNPJ:");

        jLabel9.setText("Setor:");

        javax.swing.GroupLayout jPanelFornecedoresLayout = new javax.swing.GroupLayout(jPanelFornecedores);
        jPanelFornecedores.setLayout(jPanelFornecedoresLayout);
        jPanelFornecedoresLayout.setHorizontalGroup(
            jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFornecedoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFecharTelaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonSalvarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCNPJ))
                    .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboListaFornecedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFornecedoresLayout.createSequentialGroup()
                                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldSenha)
                                    .addComponent(jTextFieldNome)
                                    .addComponent(jTextFieldLogin)))))
                    .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUsuarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextSetor)))
                .addContainerGap())
        );
        jPanelFornecedoresLayout.setVerticalGroup(
            jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedoresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboListaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelUsuarioId, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarFornecedor)
                    .addComponent(jButtonFecharTelaFornecedor))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarFornecedorActionPerformed
        int _id = 0;
        try{
            _id = Integer.parseInt(this.jLabelUsuarioId.getText());
        }
        catch(NumberFormatException ex){}
        
        String _nome = this.jTextFieldNome.getText();
        String _login = this.jTextFieldLogin.getText();
        String _senha = this.jPasswordFieldSenha.getText();
        String _cnpj = this.jTextCNPJ.getText();
        String _setor = this.jTextSetor.getText();
        
        HomeController.print("Salvar dados Fornecedor:");
        HomeController.print(""+_id);
        HomeController.print(_nome);
        HomeController.print(_login);
        HomeController.print(_senha);
        HomeController.print(_cnpj);
        HomeController.print(_setor);

        //if(jComboListaFornecedores.getSelectedItem().equals("Adicionar: Novo Usuário")){
            // próximo Id
            for (Fornecedor fornecedorFromLista : HomeController.listaFornecedores) {
                if(_id <= fornecedorFromLista.getId()){
                    _id = fornecedorFromLista.getId()+1;
                }
            }
            if(_id<=0)
                _id = 1;
            
            Fornecedor fornecedor = new Fornecedor(_id, _nome, _login, _senha, _cnpj, _setor);
            HomeController.addFornecedor2Lista(fornecedor);
//        }
//        else{
//            Usuario usuario = new Usuario(_id, _nome, _login, _senha, _nivel);
//            HomeController.updateUsuario2Lista(usuario);
//        }
        
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalvarFornecedorActionPerformed

    private void jButtonFecharTelaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharTelaFornecedorActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFecharTelaFornecedorActionPerformed

    private void jComboListaFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboListaFornecedoresActionPerformed
        if(evt.getActionCommand().equals("comboBoxChanged")){
            if(jComboListaFornecedores.getSelectedItem()==null || jComboListaFornecedores.getSelectedItem().equals("Adicionar: Novo Usuário")){
                //this.jLabelUsuarioId.setText("0");
                this.jLabelUsuarioId.setText("");
                this.jTextFieldNome.setText("");
                this.jTextFieldLogin.setText("");
                this.jPasswordFieldSenha.setText("");
                this.jTextCNPJ.setText("");
                this.jTextSetor.setText("");
            }
            else{
                for (Fornecedor fornecedorCadastrado : listaForcedoresCadastrados) {
                    if(fornecedorCadastrado.getNome().equalsIgnoreCase(jComboListaFornecedores.getSelectedItem().toString())){
                        //System.out.println("comboBoxChanged selected: " + jComboListaUsuarios.getSelectedItem() + ", " + fornecedorCadastrado.getNome());
                        this.jLabelUsuarioId.setText(""+fornecedorCadastrado.getId());
                        this.jTextFieldNome.setText(fornecedorCadastrado.getNome());
                        this.jTextFieldLogin.setText(fornecedorCadastrado.getLogin());
                        this.jPasswordFieldSenha.setText(fornecedorCadastrado.getSenha());
                        this.jTextCNPJ.setText(fornecedorCadastrado.getCnpj());
                        this.jTextSetor.setText(fornecedorCadastrado.getSetorAtuacao());
                    }
                }
            }
            
        }
    }//GEN-LAST:event_jComboListaFornecedoresActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CadastroUsuarios().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharTelaFornecedor;
    private javax.swing.JButton jButtonSalvarFornecedor;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboListaFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUsuarioId;
    private javax.swing.JPanel jPanelFornecedores;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextCNPJ;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextSetor;
    // End of variables declaration//GEN-END:variables

    public void setCamposEntrada() {
        this.jLabelUsuarioId.setText("0");
        this.jTextFieldNome.setText("");
        this.jTextFieldLogin.setText("");
        this.jPasswordFieldSenha.setText("");
        this.jPasswordFieldSenha.setText("");
    }

    public void carregarDados() {

        HomeController.print("carregarDadosUsuarios() in CadastroUsuarios");

        //this.jComboListaUsuarios = new javax.swing.JComboBox<>();

        File file = new File("projetoestoque.fornecedor.persistencia.db");
        
        ObjectInputStream in = null;
        java.util.List<Fornecedor> listaFornecedoresTmp = null;
        
        try {
            in = new ObjectInputStream(new FileInputStream(file));
            listaFornecedoresTmp = (ArrayList<Fornecedor>) in.readObject();
            //listaUsuario = listaUsuariosTmp;
            in.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HomeController.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(HomeController.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomeController.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        }
        
        if(listaFornecedoresTmp==null){
            listaFornecedoresTmp = new ArrayList<Fornecedor>();
        }
        
        listaForcedoresCadastrados = listaFornecedoresTmp;
        
        this.jComboListaFornecedores.removeAllItems();
        this.jComboListaFornecedores.addItem("Adicionar: Novo Fornecedor");
        
        for (Fornecedor fornecedor : listaFornecedoresTmp) {
            this.jComboListaFornecedores.addItem(fornecedor.getNome());
        }
    }

}
